### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by shyams80** [shyams80/pluto#2]
- [x] The queue is processed sequentially, one at a time. Change this to a multi-proc system. [plutoX](/shyams80/plutoX)
- [x] Landing page, signup link etc for pluto.studio [plutoX](/shyams80/plutoX)
- [ ] Add a pre-release step to add sample data to [plutoPy](/shyams80/plutoPy) and [plutoR](/shyams80/plutoR) 
- [ ] Make [plutoPy](/shyams80/plutoPy) available via pip
- [ ] Make [plutoR](/shyams80/plutoR) available via CRAN

**Comment by shyams80** [comment]
Landing page setup done. JupyterHub has now been moved to http://app.pluto.studio
